apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapps-deployment
  namespace: ramya123
  labels:
    app: myapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapps
  template:
    metadata:
      labels:
        app: myapps
    spec:
      containers:
      - name: docker
        image: acrregistry195.azurecr.io/dotnet-web:latest
        ports:
        - containerPort: 80
