apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: docker-hpa
  namespace: ramya123
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: docker
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50