apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: ramya123
spec:
  selector:
    app: myapps
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer