apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: ramya123
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: acrregistry195.azurecr.io/dotnet-web:latest
          ports:
            - containerPort: 80
