apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  namespace: ramya123
  labels:
    app: myapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapps
  template:
    metadata:
      labels:
        app: myapps
    spec:
      containers:
      - name: docker
        image: ramyairganti/dotnet-web:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
            memory: "300Mi"
          requests:
            cpu: "100m"
            memory: "300Mi"
        livenessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: ENV_VARIABLE_1
          valueFrom:
            configMapKeyRef:
              name: docker-configmap
              key: ENV_VARIABLE_1
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: docker-secret
              key: SECRET_KEY